project:
  type: website
  output-dir: docs

website:
  title: "Juan De La Cruz | Digital Marketing & Analytics"
  google-analytics: "G-NZ6JF0QEKB"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Digital Marketing Projects"
        href: digital-marketing-projects.qmd
      - text: "Marketing Analytics Projects"
        href: marketing-analytics-projects.qmd
      - text: "Rising Stars Muay Thai: Data-Driven Insights & Strategic Roadmap"
        href: Data-Driven-Growth-Strategy-for-Rising-Stars-Muay-Thai.qmd
      - text: "Website Traffic Analytics"
        href: website-traffic-analytics.qmd
      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: darkly
    toc: true